using System;

class ResultCalculator
{
    static void Main()
    {
        
        
        Console.WriteLine("Marksheet generated by Neha Mahto:");
        

        int marksA, marksB, marksC, sum;
        double avg;

        // Taking input
        Console.Write("Enter marks of first subject: ");
        marksA = Convert.ToInt32(Console.ReadLine());

        Console.Write("Enter marks of second subject: ");
        marksB = Convert.ToInt32(Console.ReadLine());

        Console.Write("Enter marks of third subject: ");
        marksC = Convert.ToInt32(Console.ReadLine());

        // Arithmetic operations
        sum = marksA + marksB + marksC;
        avg = sum / 3.0;

        Console.WriteLine("\nTotal obtained marks: " + sum);
        Console.WriteLine("Average percentage: " + avg);

        // Pass/Fail check using relational + logical operators
        if (marksA >= 40 && marksB >= 40 && marksC >= 40)
        {
            Console.WriteLine("Status: Student has passed");

            // Grade calculation
            if (avg >= 80)
                Console.WriteLine("Performance: Excellent (Distinction)");
            else if (avg >= 60)
                Console.WriteLine("Performance: Very Good (First Division)");
            else if (avg >= 50)
                Console.WriteLine("Performance: Good (Second Division)");
            else
                Console.WriteLine("Performance: Satisfactory (Third Division)");
        }
        else
        {
            Console.WriteLine("Status: Student has failed");
        }
    }
}